---
daily_update_hour: 14
lesson_settings: # in minutes
  min_time_for_lesson: 30
  max_time_for_lesson: 60
teacher_info:
  name: "Name Surname"
  phone: "+79999999999"
  email: "email@gmail.com"
  vk: "https://vk.com"
default_available_time:
  monday: "17:00 - 19:00"
  tuesday: "19:00 - 23:00"
  wednesday: "---"
  thursday: "17:00 - 23:00"
  friday: "---"
  saturday: "09:00 - 11:00, 14:00 - 23:00"
  sunday: "10:00 - 11:00"
faq:
  # question without question mark: answer
  Что делать, если запись на занятие создана, но время в расписании не поменялось: "Чтобы время занятия исчезло из доступного расписания, нужно чтобы учитель одобрил его. Вместе с одобрением Вам на указанную почту придет уведомление, а также в Профиле можно будет увидеть, что занятие одобрено."
  Как отменить занятие: "Самостоятельно отменить занятие на сайте нельзя, используйте форму обратной связи."
  Как перенести занятие: "Отредактировать занятие можно написав о соответствующем желании в форме обратной связи."
  Что делать, если возникла ошибка 404 или другая ошибка: "Напишите в форме обратной связи о проблеме, постарайтесь как можно детальнее рассказать о своих действиях до возникновения ошибки."
  Как поменять пароль: "Выйдите из профиля и нажмите на `Забыли пароль`."
  Можно ли удалить аккаунт: "Да, конечно. Нужно обратиться по через форме обратной связи и сообщить о своем желании."
  Почему надо кому-то писать для выполнения простейших действий: "Некоторый функционал сайта еще не реализован. В ином случае, причина заключается в необходимости быстрого реагирования на изменение в расписании, которое достигается уведомлением через форму обратной связи."
...