# Generated by Django 4.2 on 2023-04-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lesson', models.DateField(verbose_name='Дата занятия')),
                ('pupil_name', models.CharField(default='Ученик', max_length=120, verbose_name='Имя ученика')),
                ('desc', models.TextField(blank=True, verbose_name='Описание')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрено?')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['date_lesson', 'pupil_name'],
            },
        ),
    ]
