# Generated by Django 4.2 on 2023-08-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_type', models.TextField(verbose_name='Тип времени')),
                ('at', models.JSONField(verbose_name='Свободное время')),
            ],
            options={
                'verbose_name': 'Свободное время',
                'verbose_name_plural': 'Свободное время',
            },
        ),
    ]
