# Generated by Django 4.2 on 2023-08-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletimemodel',
            name='time_type',
            field=models.CharField(choices=[('default', 'Default'), ('actual', 'Actual'), ('dates', 'Dates')], max_length=7, primary_key=True, serialize=False, verbose_name='Тип времени'),
        ),
    ]
