# Generated by Django 4.2 on 2023-08-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_availabletime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabletime',
            name='id',
        ),
        migrations.AlterField(
            model_name='availabletime',
            name='time_type',
            field=models.TextField(primary_key=True, serialize=False, verbose_name='Тип времени'),
        ),
    ]
