# Generated by Django 4.2 on 2023-04-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lesson_pupil_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date_lesson', 'time_lesson', 'date_created'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='pupil_name',
            new_name='pupil',
        ),
    ]
