# Generated by Django 4.2 on 2023-04-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lesson_options_rename_pupil_name_lesson_pupil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='time_lesson',
            field=models.TextField(verbose_name='Время занятия'),
        ),
    ]
